{% set name = "pytest-html" %}
{% set version = "3.2.0" %}
{% set hash = "c4e2f4bb0bffc437f51ad2174a8a3e71df81bbc2f6894604e604af18fbe687c3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools
    - setuptools_scm
    - pip

  run:
    - python >=3.6
    - pytest >=5.0,!=6.0.0
    - pytest-metadata

test:
  imports:
    - pytest_html

about:
  home: https://github.com/pytest-dev/pytest-html
  license: MPL-2.0
  license_file: LICENSE
  summary: pytest plugin for generating HTML reports

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
