{% set name = "pytest-html" %}
{% set version = "3.1.0" %}
{% set hash = "8a7979e2411aac445870d8cad9a251ab3823bc14f77d065e9ce9a5dff86f697d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools
    - setuptools_scm
    - pip

  run:
    - python >=3.6
    - pytest >=5.0
    - pytest-metadata

test:
  imports:
    - pytest_html

about:
  home: https://github.com/pytest-dev/pytest-html
  license: MPL 2.0
  license_file: LICENSE
  license_family: OTHER
  summary: pytest plugin for generating HTML reports

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
