travis:
  secure:
    BINSTAR_TOKEN: bXINWjmPe12iqQWs7t2rB+G9tP8dKzSYMs3FW7CBMCFOf/dj9k6TkyJE+L4C4PX891vRjDUSQjmAyEddMaOIS4mNwHdnPsR9gQOzfuFfKF6RvoQzJHkPpliFY29X4kdZScFL0dJoMIGfnietUTL4HFLEisiavia0lgYDDvMZ2/rhonL22Z8nR5bF9HE2KctsHhu/Wuh8CWe0i38VM0DvvYWc1kQZVErN5+I4Tpx7x7cTCzwvTENgBDPHyEoFw4zbaRZ2jyHiXFPyluqq8DMGokZ1PIOJymKX+MrXHhEQdX/q9dMQfna0KXFwAO6GSZuYWwNpsiZjVQMih6hMitLz57vCqXpOiEqxaSbfLVYKtbPPOeeChRJPF8z+WL5FOIjS6eGfRJVq5gX6u4/n1gpClBqAurhL49B9N5QQOBLShykUgaTzh7We4h6Kw3tFHBjmL2Wm0X+ZR3DOQoAm9XFpojda0quKPAsLRoWZFgDMpvLzbGGMYbYgCqvOZQsROJnpdgpOJRaytQPyjlLC4mvSCpDAfKsbGzqY6faNU2Vg5LqpZLJ9VjjEM7dQTTU5AUI/gkPzhrap/QFqoU/LJgSStHW/wYzpEVkQ1P1XZpkrTtr3vg64yAV/9zZ+yxYdO2oke3ZzwekUJL5CehFYamy2y1Uo5w/zv+ZJ1nS6gv9xR8E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
