travis:
  secure:
    BINSTAR_TOKEN: Qglpf6I9cz2Gk8pKt+lKCzVZvLAufbMrBbdfXBqEQda2Ia6QyYUF+y8+wFZlQpSTrmajGJxn9lqFG296jcaeCO3vM9mCguMhXQMZf45E8mTI37YCP2XjjJ75DbqJOo+G5abK+5s7jx3hdZjMVwLl0Tlcv9omCmnr1uYqRRXxHxMnBD0Fcy2RHGSa5SNHpXLdRa20+u6RrXkfJPpQpaMtnE+xE4p6R89LfH8L19171B7eRXRJ8tK6fd4HIWRY58ENPr8cosGf13JW/VmN01566R0JczSGyGiwMkKq9rLNd+dM0yF53xLusEgUmwGB/RPGK9i/SxwxFZxO3b+fwAUevm2+nkMnoWZ17p3HVqbH4lQXpSL7Z+dV1YTTFS6ZnCXbyUcAOgnS3KjLa8rRAAvY7RFADgHhXlh9NMCJczRe0ndAJrkyDdUhXODiK78p6IS+QSYRcN9Q/8Rs9ROww6tHeuKWLnkNzFFbQl4Z/6794oaIwlF0ccYcQ9I2WzcD3Hy0c8SYBdMvqN/psdHc8YQJUvNCWMpUzVhZN7e6pesexSIqE+edUgC85Fi6jq5xRJtdvROyeg13x8JNdKfzPmJRjsZzsIIxqBFPUqkgbwJH1lmLT32ZMSQD3DQ9A4QdVOeXPIpggEE8YH0hbC82meSEc2/iEAmz+Dn8L7/y7+OV6JQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
